Hw dao console handler
Likh-Alex/jv-create-annotation pull request #1
Opened 2021-01-06 16:09 UTC by Likh-Alex

2021-01-06 16:35 UTC, Alex-Korzun approved these changes

2021-01-08 08:02 UTC, KseniiaMakarova requested changes

2021-01-08 08:02 UTC, KseniiaMakarova commented on src/main/java/contoller/BetConsoleHandler.java
> +            betDao.add(newBet);
let's add bet to the storage if it is not null

2021-01-08 08:02 UTC, KseniiaMakarova commented on src/main/java/dao/implementation/PersonDaoImpl.java
> +
redundant empty line

2021-01-08 08:02 UTC, KseniiaMakarova commented on src/main/java/model/Person.java
> +    int age;
what is missing?

2021-01-08 08:45 UTC, Likh-Alex commented on src/main/java/Main.java
> +
Done

2021-01-08 08:46 UTC, Likh-Alex commented on src/main/java/dao/implementation/PersonDaoImpl.java
> +
Done

2021-01-08 09:07 UTC, Likh-Alex commented on src/main/java/model/Person.java
> +    int age;
Access modifiers) Fixed

2021-01-08 09:16 UTC, Likh-Alex commented on src/main/java/contoller/BetConsoleHandler.java
> +            betDao.add(newBet);
Done

2021-01-08 09:16 UTC, Likh-Alex commented on src/main/java/contoller/BetConsoleHandler.java
> +                try {
Done, refactored for two catch blocks

2021-01-08 09:46 UTC, Likh-Alex commented on src/main/java/contoller/BetConsoleHandler.java
> +public class BetConsoleHandler {
Done, moved handling of the `Person` also into the `ConsoleHandler`, now there is only one `ConsoleHandler` with one `handle` method.

2021-01-08 09:51 UTC, Likh-Alex commented on src/main/java/contoller/BetConsoleHandler.java
> +    Scanner scanner = new Scanner(System.in);
Missing access modifiers. Made the `scanner` a local variable

2021-01-08 13:36 UTC, KseniiaMakarova requested changes

2021-01-08 13:36 UTC, KseniiaMakarova commented on src/main/java/dao/PersonDao.java
> +
redundant empty line

2021-01-08 13:36 UTC, KseniiaMakarova commented on src/main/java/dao/PersonDao.java
> +    Bet getBet(Person person);
let's remove this method for now and not bind Person and Bet

2021-01-08 13:36 UTC, KseniiaMakarova commented on src/main/java/dao/implementation/PersonDaoImpl.java
> +
redundant empty line - please remove

2021-01-08 13:36 UTC, KseniiaMakarova commented on src/main/java/model/Person.java
> +    private Bet bet;
```suggestion
```

2021-01-08 13:39 UTC, Likh-Alex commented on src/main/java/dao/PersonDao.java
> +
Deleted

2021-01-08 13:39 UTC, Likh-Alex commented on src/main/java/dao/PersonDao.java
> +    Bet getBet(Person person);
Removed

2021-01-08 13:40 UTC, Likh-Alex commented on src/main/java/dao/implementation/PersonDaoImpl.java
> +
Removed as well, thank you.

2021-01-08 13:41 UTC, Likh-Alex commented on src/main/java/model/Person.java
> +    private Bet bet;
removed with methods as well.

2021-01-08 13:51 UTC, KseniiaMakarova approved these changes

2021-01-08 16:24 UTC, merged